---
title: "Folder report"
author: "Lukáš Hejtmánek"
date: "22 December 2019"
output: html_document
---

```{r setup, include=FALSE}
library(fgu.avoidance)
library(knitr)
library(ggpubr)
source(file.path("functions", "results-formatting.R"))
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r}
data_folder <- file.path("..", "..", "data", "run35-house-session")
apparatus_image <- file.path("..", "images", "apparatus.png")
obj <- load_folder(data_folder)
obj <- add_areas(obj)
```

```{r, results='asis'}
cat("<h3>folder ", data_folder, "</h3>")
cat('<p><div class="row">')
  cat('<div class="col-md-12">')
    plt <- create_heatmap(obj, bins = 100, background = apparatus_image)
    print(plt)
  cat("</div>")
cat("</p></div>")
```

```{r results='asis'}
cat('<div class="container">')
cat('<div class="row">')
for(n in 1:length(obj)){
  cat('<div class="row">')
    plt_path <- plot_path(obj[[n]], center = NULL, background = apparatus_image)
    plt_presence <- plot_area_presence(obj[[n]])
    cat('<div class="col-md-6">')
      print(ggarrange(plt_path, plt_presence, ncol = 1, nrow = 2, heights = c(3,1)))
    cat('</div>')
    cat('<div class="col-md-3">')
      cat('<h3>', names(obj)[n], '</h3>')
      cat(session_results_output(session_results(obj[[n]])))
    cat("</div>")
  cat("</div>")
} 
cat("</div>")
```